services:
  postgres:
    image: postgres:latest
    container_name: cinema-db
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1337cs
      POSTGRES_DB: cinema_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
